PAL_OSAL: Added from firmware.

diff --git a/external/rootfs_overlay/etc/init.d/system_setup b/external/rootfs_overlay/etc/init.d/system_setup
--- a/external/rootfs_overlay/etc/init.d/system_setup
+++ b/external/rootfs_overlay/etc/init.d/system_setup
@@ -5,83 +5,79 @@ PATH=/usr/local/bin:/usr/bin:/bin:/sbin
 . /etc/init.d/init_utilities
 
 mount_if_not_mounted() {
-    if [ $# -lt 3 -o $# -gt 4 ]; then
-        echo "ERROR: Invalid number of variables passed to mount function"
-        exit 1
-    fi
+	if [ $# -lt 3 -o $# -gt 4 ]; then
+		echo "ERROR: Invalid number of variables passed to mount function"
+		exit 1
+	fi
 
-    DEST_PATH="$1"
-    SRC_PATH="$2"
-    TYPE="$3"
-    if [ $# -eq 4 ]; then
-        OPTIONS="$4"
-    else
-        OPTIONS=""
-    fi
+	DEST_PATH="$1"
+	SRC_PATH="$2"
+	TYPE="$3"
+	if [ $# -eq 4 ]; then
+		OPTIONS="$4"
+	else
+		OPTIONS=""
+	fi
 
-    mount | grep -q "on $DEST_PATH "
-    if [ $? -eq 1 ]; then
-        mount -t $TYPE $OPTIONS $SRC_PATH $DEST_PATH
-    else
-        echo "INFO: $DEST_PATH was already mounted; skipping"
-    fi
+	mount | grep -q "on $DEST_PATH "
+	if [ $? -eq 1 ]; then
+		mount -t $TYPE $OPTIONS $SRC_PATH $DEST_PATH
+	else
+		echo "INFO: $DEST_PATH was already mounted; skipping"
+	fi
 }
 
 start_function() {
-    # Setup the normal psuedo-filesystems
-    # Mount checking cannot be done if /proc is not mount, and because /proc
-    #   cannot be unmounted on a running system we will always try to mount.
-    #   This may cause an annoying message on re-mounts of /proc, but there is
-    #   no simple way to address it in this init script.
-    mkdir -p proc tmp sys var dev
-    mount -a
-    if /scripts/is_gateway ; then
-        mount_if_not_mounted "/dev" "tmpfs" "tmpfs" "-o size=2m"
-        mknod /dev/null c 1 3
-        [ ! -d /dev/pts ] && mkdir -p --mode=a+rwx /dev/pts
-    fi;
-    mount_if_not_mounted "/dev/pts" "devpts" "devpts"
+	# Setup the normal psuedo-filesystems
+	# Mount checking cannot be done if /proc is not mount, and because /proc
+	#   cannot be unmounted on a running system we will always try to mount.
+	#   This may cause an annoying message on re-mounts of /proc, but there is
+	#   no simple way to address it in this init script.
+	mkdir -p proc tmp sys var dev
+	mount -a
+	mount_if_not_mounted "/dev" "tmpfs" "tmpfs" "-o size=2m"
+	mknod /dev/null c 1 3
+	[ ! -d /dev/pts ] && mkdir -p --mode=a+rwx /dev/pts
+	mount_if_not_mounted "/dev/pts" "devpts" "devpts"
 
-    mkdir -p --mode=a+rwx /var/log /var/run /var/lock
-    touch /var/log/lastlog
-    if [ ! -e /var/log/messages ]; then
-        ln -s /tmp/messages /var/log/messages
-    fi
+	mkdir -p --mode=a+rwx /var/log /var/run /var/lock
+	touch /var/log/lastlog
+	if [ ! -e /var/log/messages ]; then
+		ln -s /tmp/messages /var/log/messages
+	fi
 
-    # Create a mount point in /tmp
-    mkdir -p /tmp/mnt
+	# Create a mount point in /tmp
+	mkdir -p /tmp/mnt
 
-    # Start syslog
-    syslogd -O /tmp/messages
+	# Start syslog
+	syslogd -O /tmp/messages
 
-    # Setup the RTC
-    make_dev rtc rtc 10 135
+	# Setup the RTC
+	make_dev rtc rtc 10 135
 }
 
 stop_function() {
-    rm -f /dev/rtc
-    killall syslogd
-    umount /var
-    umount /tmp
-    umount /sys
-    umount /dev/pts
-    if /scripts/is_gateway ; then
-        umount -l /dev
-    fi;
+	rm -f /dev/rtc
+	killall syslogd
+	umount /var
+	umount /tmp
+	umount /sys
+	umount /dev/pts
+	umount -l /dev
 }
 
 case $1 in
-    "start")
-        start_function
-        ;;
-    "stop")
-        stop_function
-        ;;
-    "restart")
-        stop_function
-        start_function
-        ;;
-    *)
-        echo "Usage: $0 {start|stop|restart}"
+	"start")
+		start_function
+	;;
+	"stop")
+		stop_function
+	;;
+	"restart")
+		stop_function
+		start_function
+	;;
+	*)
+		echo "Usage: $0 {start|stop|restart}"
 esac
 
